site_name: Photoshop User Documentation
nav:
  - Home: "Introduction.md"
  - Layer Masks: "Layer Mask.md"
  - Animations: "animations.md"
  - Exporting: "Exporting.md"
  - Troubleshooting: Troubleshooting.md
  - Glossary: "Glossary.md"
  


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  icon:
    admonition:
       warning: octicons/alert-16
       note: octicons/tag-16
       warning: octicons/alert-16

